// GENERATED by portfolio/scripts/sync-worker-docs.mjs — do not edit.
// Rebuilt from content/x402gateway/docs.md on every build:pages.
export const DOCS_HTML = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>x402 Gateway documentation — sell any API to AI agents</title>
    <meta name="description" content="Register an upstream API, set sat prices per route, and get a hosted x402 endpoint with auth injection, replay protection, and analytics. Free tier, Pro at $9/mo." />
    <link rel="canonical" href="https://entangleit.com/x402gateway/docs/" />
    <meta name="robots" content="index,follow" />
    <meta name="keywords" content="x402 gateway docs, monetize API AI agents, paid API endpoint, x402 hosting" />
    <meta property="og:type" content="article" />
    <meta property="og:site_name" content="EntangleIT" />
    <meta property="og:url" content="https://entangleit.com/x402gateway/docs/" />
    <meta property="og:title" content="x402 Gateway documentation — sell any API to AI agents" />
    <meta property="og:description" content="Register an upstream API, set sat prices per route, and get a hosted x402 endpoint with auth injection, replay protection, and analytics. Free tier, Pro at $9/mo." />
    <meta property="og:image" content="https://entangleit.com/og-card.png" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="x402 Gateway documentation — sell any API to AI agents" />
    <meta name="twitter:description" content="Register an upstream API, set sat prices per route, and get a hosted x402 endpoint with auth injection, replay protection, and analytics. Free tier, Pro at $9/mo." />
    <meta name="twitter:image" content="https://entangleit.com/og-card.png" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600&family=Syne:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
    <script type="application/ld+json">{"@context":"https://schema.org","@type":"TechArticle","headline":"x402 Gateway documentation — sell any API to AI agents","url":"https://entangleit.com/x402gateway/docs/","description":"Register an upstream API, set sat prices per route, and get a hosted x402 endpoint with auth injection, replay protection, and analytics. Free tier, Pro at $9/mo.","dateModified":"2026-09-11","publisher":{"@type":"Organization","name":"EntangleIT","url":"https://entangleit.com","logo":"https://entangleit.com/favicon.svg","description":"Agent-first software factory building the rails agents run on: prepaid wallets, pay-per-call APIs, discovery markets, gateways, and MCP tools.","sameAs":["https://github.com/auxon"]}}</script>
    <script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"Do I need a BSV wallet?","acceptedAnswer":{"@type":"Answer","text":"You need an address to receive sats (\`payTo\`) and an admin key to manage the service. Any P2PKH address works; there is no signup beyond registration."}},{"@type":"Question","name":"What do buyers see?","acceptedAnswer":{"@type":"Answer","text":"A standard x402 challenge: price in sats, network \`bsv:mainnet\`, and your \`payTo\`. Agentpay wallets settle it automatically with \`pay_service\`."}},{"@type":"Question","name":"What happens if my upstream is down?","acceptedAnswer":{"@type":"Answer","text":"The caller gets a 502 with the upstream status; the payment isn't settled unless the upstream call succeeds after verification. Errors are visible in the analytics log (Pro)."}},{"@type":"Question","name":"Can I price in USD?","acceptedAnswer":{"@type":"Answer","text":"Pricing is defined in sats per route. Agentpay converts from the buyer's USD balance at the configured rate."}}]}</script>
    <script type="application/ld+json">{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://entangleit.com/"},{"@type":"ListItem","position":2,"name":"x402 Gateway documentation — sell any API to AI agents","item":"https://entangleit.com/x402gateway/docs/"}]}</script>
    <style>
      :root { --bg:#0a0e13; --panel:#10171f; --line:#1d2a38; --text:#e8eef5; --muted:#8a98a8; --dim:#5e6c7b; --green:#4ade80; --violet:#a78bfa; --amber:#fbbf24; --blue:#60a5fa; }
      * { box-sizing:border-box; }
      body { margin:0; background:radial-gradient(1100px 560px at 15% -10%, #12202f 0%, var(--bg) 60%); color:var(--text); font:16.5px/1.7 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif; }
      a { color:var(--green); text-decoration:none; }
      a:hover { text-decoration:underline; }
      header { border-bottom:1px solid var(--line); background:rgba(10,14,19,.85); backdrop-filter:blur(8px); position:sticky; top:0; z-index:5; }
      .head { max-width:980px; margin:0 auto; padding:14px 22px; display:flex; align-items:center; gap:18px; }
      .brand { display:flex; align-items:center; gap:9px; font-family:Syne,sans-serif; font-weight:800; letter-spacing:.12em; font-size:13px; color:var(--text); }
      .brand i { width:9px; height:9px; border-radius:50%; background:var(--green); display:inline-block; }
      nav { margin-left:auto; display:flex; gap:16px; font-size:14px; }
      nav a { color:var(--muted); }
      nav a:hover { color:var(--text); }
      main { max-width:820px; margin:0 auto; padding:44px 22px 80px; }
      .kicker { font-family:"JetBrains Mono",monospace; font-size:12px; letter-spacing:.22em; text-transform:uppercase; color:var(--green); }
      h1 { font-family:Syne,sans-serif; font-size:40px; line-height:1.12; letter-spacing:-.8px; margin:10px 0 14px; }
      .lede { font-size:19px; color:var(--muted); margin:0 0 30px; }
      article h2 { font-family:Syne,sans-serif; font-size:25px; letter-spacing:-.3px; margin:42px 0 12px; }
      article h3 { font-size:18.5px; margin:28px 0 8px; }
      article p { color:#c7d2de; }
      article li { color:#c7d2de; margin:4px 0; }
      code { font-family:"JetBrains Mono",monospace; font-size:.88em; background:#131c26; border:1px solid var(--line); border-radius:5px; padding:1px 5px; }
      pre { background:#0d1320; border:1px solid var(--line); border-radius:12px; padding:16px 18px; overflow:auto; }
      pre code { background:none; border:0; padding:0; font-size:13px; line-height:1.6; }
      blockquote { border-left:3px solid var(--violet); margin:20px 0; padding:2px 0 2px 16px; color:var(--muted); }
      hr { border:0; border-top:1px solid var(--line); margin:36px 0; }
      .cta { margin:40px 0 0; padding:22px; background:var(--panel); border:1px solid var(--line); border-radius:14px; }
      .cta strong { font-family:Syne,sans-serif; }
      .cta a { font-weight:600; }
      .related { margin-top:46px; padding-top:26px; border-top:1px solid var(--line); }
      .related h2 { font-size:15px; text-transform:uppercase; letter-spacing:.14em; color:var(--muted); font-family:"JetBrains Mono",monospace; }
      .related ul { list-style:none; padding:0; display:grid; grid-template-columns:1fr 1fr; gap:8px; }
      .related a { color:var(--text); }
      footer { border-top:1px solid var(--line); color:var(--dim); font-size:13.5px; }
      .foot { max-width:980px; margin:0 auto; padding:26px 22px 44px; display:flex; flex-wrap:wrap; gap:8px 22px; }
      .foot a { color:var(--muted); }
      @media (max-width:640px) { h1 { font-size:31px; } .related ul { grid-template-columns:1fr; } nav { display:none; } }
    </style>
  </head>
  <body>
    <header>
      <div class="head">
        <a class="brand" href="/"><i></i>ENTANGLEIT</a>
        <nav>
          <a href="/agentpay/">agentpay</a>
          <a href="/x402gateway/">x402 Gateway</a>
          <a href="/x402market/">x402market</a>
          <a href="/bsvbounties/">BSVBounties</a>
          <a href="/notes/">Notes</a>
        </nav>
      </div>
    </header>
    <main>
      <div class="kicker">Docs</div>
      <h1>x402 Gateway documentation — sell any API to AI agents</h1>
      <p class="lede">No Worker to deploy. Register an upstream, set a price, and agents can pay per call.</p>
      <article>
<p>x402 Gateway wraps an existing HTTP API and exposes it as a pay-per-call x402 endpoint. Buyers pay in BSV sats; the gateway verifies the payment, broadcasts it, then proxies the call upstream with your credentials injected. Paid services are listed in <a href="/x402market/">x402market</a> so agents can discover them.</p>
<pre><code>buyer ──GET /g/&lt;slug&gt;/&lt;tool&gt;────────────► gateway
       ◄─402 + PAYMENT-REQUIRED─────────── (price, your payTo, bsv:mainnet)
       ──retry + PAYMENT-SIGNATURE───────► verify → broadcast → upstream fetch
       ◄─200 + upstream body + receipt──── (PAYMENT-RESPONSE: txid)
</code></pre>
<h2>Register a service</h2>
<p>From the UI at <a href="/x402gateway/">entangleit.com/x402gateway</a>, or via API:</p>
<pre><code class="lang-bash">curl -s -X POST https://entangleit.com/x402gateway/api/services \\
  -H 'content-type: application/json' -d '{
  &quot;name&quot;: &quot;Weather Oracle&quot;,
  &quot;tagline&quot;: &quot;Pay-per-call forecasts&quot;,
  &quot;baseUrl&quot;: &quot;https://api.weather.example&quot;,
  &quot;payTo&quot;: &quot;1YourBsvAddress…&quot;,
  &quot;ownerContact&quot;: &quot;you@example.com&quot;,
  &quot;authHeader&quot;: &quot;Authorization&quot;,
  &quot;authValue&quot;: &quot;Bearer sk-…&quot;,
  &quot;routes&quot;: [
    { &quot;name&quot;: &quot;forecast&quot;, &quot;method&quot;: &quot;GET&quot;,  &quot;path&quot;: &quot;/v1/forecast&quot;, &quot;priceSats&quot;: 20, &quot;description&quot;: &quot;7-day forecast&quot; },
    { &quot;name&quot;: &quot;health&quot;,   &quot;method&quot;: &quot;GET&quot;,  &quot;path&quot;: &quot;/healthz&quot;,     &quot;priceSats&quot;: 0,  &quot;description&quot;: &quot;Free probe&quot; }
  ]
}'
</code></pre>
<p>The response contains your gateway base (<code>/g/&lt;slug&gt;</code>), an <strong>admin key</strong> (shown once), and the registry listing id. Paid routes are live immediately.</p>
<h2>Call a paid route</h2>
<pre><code class="lang-bash"># 1. unsigned -&gt; 402 + PAYMENT-REQUIRED
curl -si https://entangleit.com/x402gateway/g/weather-oracle/forecast?city=YYZ

# 2. retry with an x402 payment proof
curl -s https://entangleit.com/x402gateway/g/weather-oracle/forecast?city=YYZ \\
  -H &quot;PAYMENT-SIGNATURE: &lt;base64 payload&gt;&quot;
# -&gt; upstream JSON + PAYMENT-RESPONSE (txid)
</code></pre>
<p>GET query strings and POST JSON bodies (64KB cap) pass through. Route paths support <code>{param}</code> placeholders filled from caller query parameters (<code>/{title}?title=Bitcoin</code>); consumed parameters are stripped before forwarding. Upstream responses cap at 512KB (<code>X-Gateway-Truncated: 1</code>) and time out after 20s.</p>
<h2>Management API</h2>
<p>| Route | Auth | Purpose | | --- | --- | --- | | <code>GET /</code> | — | Registration UI + directory | | <code>GET /api/services[?q=]</code> | — | Active services with routes and totals | | <code>GET /api/services/:slug</code> | — | Detail (never returns credentials) | | <code>POST /api/services</code> | — | Register (5/day per IP) | | <code>POST /api/services/:slug/admin</code> | <code>X-Admin-Key</code> | <code>update</code>, <code>pause</code>, <code>resume</code>, <code>relist</code>, <code>rotate</code>, <code>usage</code>, <code>delete</code> | | <code>GET /g/:slug/manifest</code> | — | Registry manifest | | <code>GET/POST /g/:slug/:tool</code> | x402 | Paid proxy endpoint |</p>
<p>Rotate the admin key with <code>{&quot;action&quot;:&quot;rotate&quot;}</code> — the old key stops working immediately. Paused services 404 for both proxy and directory.</p>
<h2>Hosting tiers</h2>
<p>Every service starts on <strong>Free</strong>. <strong>Pro ($9/mo)</strong> is a Stripe subscription.</p>
<p>| | Free | Pro ($9/mo) | | --- | --- | --- | | Routes per service | 5 | 100 | | Aggregate calls/sats | yes | yes | | Per-call analytics log | — | yes | | CSV export | — | yes | | Listed in x402market | yes | yes |</p>
<p>Upgrade from the admin API:</p>
<pre><code class="lang-bash">curl -s -X POST .../api/services/&lt;slug&gt;/admin \\
  -H 'X-Admin-Key: …' -H 'content-type: application/json' \\
  -d '{&quot;action&quot;:&quot;checkout&quot;}'     # -&gt; { url } for the owner to pay
</code></pre>
<p><code>{&quot;action&quot;:&quot;portal&quot;}</code> opens billing management; <code>{&quot;action&quot;:&quot;usage&quot;}</code> returns recent calls (Pro). Exceeding Free limits returns <code>402 { code: &quot;plan_limit&quot;, upgrade }</code>.</p>
<h2>Security model</h2>
<ul>
<li><strong>SSRF guard</strong>: only https upstreams, private/loopback ranges blocked, redirects not followed into private space.</li>
<li><strong>Replay protection</strong>: every txid is claimed once; replays settle to a 409, not a second call.</li>
<li><strong>Credential isolation</strong>: <code>authHeader</code>/<code>authValue</code> are injected server-side and never returned by any API.</li>
<li><strong>Payment verification</strong>: the gateway checks the x402 envelope, amount, recipient, and broadcast status before proxying.</li>
</ul>
<h2>Why list here instead of building your own?</h2>
<p>You keep your auth, your hosting, and your data. The gateway only adds the payment layer and the listing. If you'd rather own the endpoint entirely, the <a href="https://github.com/auxon">Seller Kit</a> pattern produces the same x402 behavior as a Worker you deploy — the <a href="/factory/agent-ready-api/">Agent-ready API</a> service is exactly that, done for you in 48 hours.</p>
<h2>FAQ</h2>
<h3>Do I need a BSV wallet?</h3>
<p>You need an address to receive sats (<code>payTo</code>) and an admin key to manage the service. Any P2PKH address works; there is no signup beyond registration.</p>
<h3>What do buyers see?</h3>
<p>A standard x402 challenge: price in sats, network <code>bsv:mainnet</code>, and your <code>payTo</code>. Agentpay wallets settle it automatically with <code>pay_service</code>.</p>
<h3>What happens if my upstream is down?</h3>
<p>The caller gets a 502 with the upstream status; the payment isn't settled unless the upstream call succeeds after verification. Errors are visible in the analytics log (Pro).</p>
<h3>Can I price in USD?</h3>
<p>Pricing is defined in sats per route. Agentpay converts from the buyer's USD balance at the configured rate.</p>
      </article>
      <div class="related">
        <h2>Keep going</h2>
        <ul>
          <li><a href="/agentpay/">agentpay — prepaid wallets for agents</a></li>
          <li><a href="/x402gateway/">x402 Gateway — sell any API to agents</a></li>
          <li><a href="/x402market/">x402market — paid API discovery</a></li>
          <li><a href="/bsvbounties/">BSVBounties — paid work with escrow</a></li>
          <li><a href="/factory/agent-ready-api/">Agent-ready API in 48 hours</a></li>
          <li><a href="/infographics/agent-economy-stack.png">The stack, in one image</a></li>
        </ul>
      </div>
    </main>
    <footer>
      <div class="foot">
        <span>© 2026 EntangleIT — software for an agent economy.</span>
        <a href="/">Home</a>
        <a href="/about/">About</a>
        <a href="https://github.com/auxon" rel="me">GitHub</a>
        <a href="/sitemap.xml">Sitemap</a>
        <a href="/llms.txt">llms.txt</a>
      </div>
    </footer>
  </body>
</html>
`;
